# Map and path search
TimeoutRRT: 0.02

# Dynamic limits
MaxBdrMag: 2.1
MaxTiltAngle: 1.05

# Vehicle
GravAcc: 9.8

# Trajectory optimization
WeightT: 20.0
ChiVec: [1.0e+4, 1.0e+4, 1.0e+4, 1.0e+4]
SmoothingEps: 1.0e-2
IntegralIntervs: 16
RelCostTol: 1.0e-5
